language: java
sudo: false

addons:
  apt:
    packages:
      - openjdk-6-jdk

matrix:
  include:
    - jdk: openjdk6
      env: CUSTOM_MVN_VERION="3.1.1"
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2

# ensures that Maven 3.1.1 is installed for use with OpenJDK 6
before_install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      unzip -qq apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      export M2_HOME=$PWD/apache-maven-${CUSTOM_MVN_VERION};
      export PATH=$M2_HOME/bin:$PATH;
      mvn -version;
    fi

